name: Deploy API (password-based)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy app.py to VM using sshpass
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" scp -o StrictHostKeyChecking=no app.py rummankhan@35.203.70.105:/home/rummankhan/app.py

      - name: Run Flask app remotely
        run: |
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no rummankhan@35.203.70.105 << 'EOF'
            pkill -f app.py || true
            nohup python3 /home/rummankhan/app.py > output.log 2>&1 &
          EOF
