name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clean up old app and code
        run: |
          ssh -o StrictHostKeyChecking=no rummankhan@35.203.70.105 << 'EOF'
            sudo pkill -f app.py || true
            rm -rf ~/hello_api || true
            mkdir ~/hello_api
          EOF

      - name: Copy new app to VM
        run: |
          scp -o StrictHostKeyChecking=no app.py rummankhan@35.203.70.105:~/hello_api/

      - name: Start Flask App
        run: |
          ssh -o StrictHostKeyChecking=no rummankhan@35.203.70.105 << 'EOF'
            sudo nohup python3 ~/hello_api/app.py > ~/hello_api/output.log 2>&1 &
          EOF
